// ============================================================
// YOTEC — Execution Engine
// ============================================================

import { store, generateId } from './state.js';

class OutputGenerator {
    static generateResponse(workerId, role, title, instructions) {
        const timestamp = Date.now();
        const id = generateId('out');

        let content = '';
        let format = 'txt';
        let qaStatus = 'pending';

        // Route based on worker role/department
        if (role.includes('Backend') || role.includes('Frontend') || role.includes('DevOps')) {
            format = 'ts';
            content = `// ==========================================================
// YOTEC Auto-Generated Module
// Task: ${title}
// Author: ${workerId} (${role})
// ==========================================================

import React, { useState, useEffect } from 'react';

/**
 * Instruction context:
 * ${instructions}
 */

export const GeneratedComponent = () => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulated API payload based on requirements
    setTimeout(() => {
      setData({ status: 'active', metric: 98.5 });
      setLoading(false);
    }, 800);
  }, []);

  if (loading) return <div className="loader blur-pulse">Initializing System...</div>;

  return (
    <div className="yotec-module-container">
      <h3>{data.status === 'active' ? 'System Online' : 'System Offline'}</h3>
      <div className="metric-display">Efficiency: {data.metric}%</div>
    </div>
  );
};

export default GeneratedComponent;
`;
        } else if (role.includes('Designer') || role.includes('Visual')) {
            format = 'svg';
            const color1 = ['#00d4ff', '#ff6bff', '#ffd700', '#00ff9d'][Math.floor(Math.random() * 4)];
            const color2 = ['#7b6cf6', '#ff4d6d', '#ff8c42', '#4cc9f0'][Math.floor(Math.random() * 4)];

            content = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 300" width="100%" height="100%">
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:${color1};stop-opacity:1" />
      <stop offset="100%" style="stop-color:${color2};stop-opacity:1" />
    </linearGradient>
    <filter id="glow">
      <feGaussianBlur stdDeviation="4" result="coloredBlur"/>
      <feMerge>
        <feMergeNode in="coloredBlur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>
  <rect width="100%" height="100%" fill="#070915" />
  
  <!-- YOTEC Logo Concept -->
  <g transform="translate(200, 140)" filter="url(#glow)">
    <circle cx="0" cy="0" r="60" fill="none" stroke="url(#grad1)" stroke-width="8" />
    <polygon points="0,-30 25,15 -25,15" fill="url(#grad1)" />
    <circle cx="0" cy="0" r="85" fill="none" stroke="rgba(255,255,255,0.1)" stroke-width="2" stroke-dasharray="10, 5" />
  </g>
  
  <text x="50%" y="260" font-family="'Space Grotesk', sans-serif" font-size="28" font-weight="700" fill="#e8eaf6" text-anchor="middle" letter-spacing="4">${title.toUpperCase()}</text>
  <text x="50%" y="280" font-family="monospace" font-size="10" fill="#8892b0" text-anchor="middle">GENERATED BY ${workerId} • ${new Date().toLocaleDateString()}</text>
</svg>`;
        } else if (role.includes('Curriculum') || role.includes('Learning') || role.includes('Knowledge')) {
            format = 'md';
            content = `# 📚 Learning Module: ${title}

## Overview
This interactive module is designed to upskill technical teams on modern AI workflows, addressing the requirements set forth in the briefing.

> **Instruction Context:**
> ${instructions}

---

## 1. Core Principles

- **Autonomy via Delegation:** Moving away from micromanagement towards outcome-based instructions.
- **Continuous Validation (QA):** Why passive reviews fail and active SENTINEL-style validation succeeds.
- **Energy Preservation:** The mathematics of cognitive load in AI agents and humans alike.

## 2. Practical Application

### Scenario A
You are asked to build a new feature. Instead of writing the code, draft a multi-agent prompt that assigns backend, frontend, and QA tasks simultaneously.

### Quiz Checkpoint
**Q1: What is the primary cause of latency in a multi-agent system?**
A) Hardware limits
B) Dependency deadlocks (Correct)
C) Token limits

## 3. Next Steps
Students completing this module will automatically unlock the advanced "Cross-Department Orchestration" badge.

---
*Created automatically by ${workerId} (${role})*
`;
        } else if (role.includes('Copywriter') || role.includes('Storyteller') || role.includes('Social')) {
            format = 'md';
            content = `# 📣 Content Draft: ${title}

## Summary Draft (For Press/Blog)
YOTEC is thrilled to announce a significant breakthrough in autonomous enterprise architecture. Our latest systemic upgrade introduces fully functional multi-agent execution, allowing AI workers not just to simulate progress, but to tangibly generate, validate, and deliver complex artifacts at unprecedented scale.

## Social Media Hooks (Twitter/X)
🧵 **Thread Option 1:**
1/5 Management is dead. Orchestration is the future. Here is how YOTEC just replaced an entire middle-management layer with specialized AI routing nodes. 👇

2/5 By giving each worker node an \`execute()\` function rather than a \`simulate()\` function, we've broken the barrier between chat-based AI and operational AI...

## Email Sequence Draft
**Subject:** Welcome to the new standard of productivity ⚡

Hi {Name},

You've probably heard about AI taking jobs. What we've built at YOTEC is different. We're giving you an entire *company* of pristine functional intelligence, ready to execute on your command.

Let's look at the numbers...

---
> **Based on prompt:** ${instructions}
`;
        } else if (role.includes('Data') || role.includes('Analyst') || role.includes('BI')) {
            format = 'json';
            content = JSON.stringify({
                reportTitle: title,
                generatedBy: workerId,
                timestamp: new Date().toISOString(),
                datasetSize: '1.4TB',
                insights: [
                    "Cross-department dependencies are causing a 14% latency in delivery timelines.",
                    "Design workers show the highest energy retention rate across all sprint cycles.",
                    "QA rejection rates hit a local maximum on Thursdays, suggesting systemic Friday rollout fatigue."
                ],
                metrics: {
                    uptime: 99.99,
                    avgTaskCompletionSeconds: 12.4,
                    errorRate: 0.003
                },
                forecast: "Assuming current velocity, Q3 deliverables will be met 4 days ahead of schedule."
            }, null, 2);
        } else {
            // Default / generic text task
            format = 'txt';
            content = `Task Report: ${title}\nExecutor: ${workerId}\n\nI have reviewed the instructions:\n"${instructions}"\n\nThe task has been executed successfully. I have optimized the workflow parameters and run preliminary checks. All systems nominal.\n\nEnergy consumed: 4%\nCompletion Time: ${Math.random().toFixed(2)}s\nStatus: Awaiting SENTINEL review.`;
        }

        return {
            id,
            workerId,
            taskType: role,
            title,
            content,
            format,
            timestamp,
            qaStatus
        };
    }
}

export class ExecutionEngine {
    static async runTask(workerId, title, instructions) {
        const state = store.state;
        const worker = state.workers[workerId];
        if (!worker) return null;

        // Simulate thinking/execution time
        const waitTime = 1500 + Math.random() * 2500;
        await new Promise(r => setTimeout(r, waitTime));

        // Generate actual output
        const output = OutputGenerator.generateResponse(workerId, worker.role, title, instructions);

        // Add to repository
        store.dispatch({ type: 'ADD_OUTPUT', payload: output });

        // Decrease worker energy slightly
        const newEnergy = Math.max(10, worker.energy - Math.floor(Math.random() * 8 + 2));
        store.dispatch({ type: 'UPDATE_WORKER', payload: { id: workerId, energy: newEnergy } });

        // Fire activity log
        store.dispatch({
            type: 'ADD_ACTIVITY',
            payload: {
                id: generateId('act'),
                time: Date.now(),
                type: 'execution',
                icon: '⚙️',
                text: `${worker.name} executed task and generated output: "${title}"`
            }
        });

        return output;
    }
}
